# Generated by Django 3.0.5 on 2021-06-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210616_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.Categories', verbose_name='категория'),
        ),
    ]
