# Generated by Django 3.0.5 on 2021-06-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210616_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_titles', to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Выберите жанр из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_titles', to='api.Genres'),
        ),
    ]
