# Generated by Django 3.0.5 on 2021-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210616_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Выберите жанр из списка', null=True, related_name='genre_titles', to='api.Genres'),
        ),
    ]
