# Generated by Django 3.0.5 on 2021-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Выберите жанр из списка', related_name='genre_titles', to='api.Genres'),
        ),
    ]
